### ISSUE TITLE
Multivariate data: which ones are padded, and are there unpadded versions?

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml_repo#1]

**Comment by MatthewMiddlehurst** [comment]
So, some candidates i found after a quick check are: JapaneseVowels, SpokenArabicDigits and CharacterTrajectories, which all seem to have strings of 0's at the end of channels. I have updated these locally to use ?'s instead (and made backups just in case).

InsectWingbeat appears to be padded at both the beginning and end. From what i gathered from Michael I believe the start point for every instance is start point of the largest series from the original audio, and the end point is the end of the largest series. It may be better to change this to have each instance start at its own start point and pad with ?'s similar to other unequal length problems.

**Comment by TonyBagnall** [comment]
OK, will upload the non-zero padded versions when michael sorts out Insects next week. We should add a transformer/filter to zero/mean pad

**Comment by MJFlynn** [comment]
Insect wingbeat is updated. Run ED_I on it just to sanity check it loads etc ok.

**Comment by TonyBagnall** [comment]
updated it all on the website
