### ISSUE TITLE
[DONATION] TiSeLac dataset

### ISSUE THREAD

**Issue by MartinoGonzales** [uea-machine-learning/tsml_repo#13]
This is the original dataset that I used for my MSc dissertation. 
The TiSeLac dataset represent a Land Cover Classification problem. 
The description of the single files can be found in the readme.txt 

Given that the files are too big for the upload limit the folder can be found at the following OneDrive link : https://ueanorwich-my.sharepoint.com/:f:/g/personal/fax14yxu_uea_ac_uk/EpJnfJFRGNpJrI3oEj4KGSQBvQXt8ZOQUwl3ZlxYWglbxA?e=9h0dPd

The data represents a multivariate problem. For a complete description of the dataset we suggest to look at the original web page of it : https://sites.google.com/site/dinoienco/tiselc

**Comment by TonyBagnall** [comment]
this is a multivariate problem where a case is a pixel, measurements taken over 23 time points (assume days), with 10 dimensions:  7 surface reflectances (Ultra Blue, Blue, Green, Red, NIR, SWIR1 and SWIR2) plus 3 indices (NDVI, NDWI and BI). Class values relate to one of 9 land cover types
class values:
Class ID | Class Name | # Instances
1 | Urban Areas | 16000
2 | Other built-up surfaces | 3236
3 | Forests | 16000
4 | Sparse Vegetation | 16000
5 | Rocks and bare soil | 12942
6 | Grassland | 5681
7 | Sugarcane crops | 7656
8 | Other crops | 1600
9 | Water | 2599

**Comment by TonyBagnall** [comment]
sorted https://www.timeseriesclassification.com/description.php?Dataset=Tiselac
