### ISSUE TITLE
[ISSUE] ItalyPowerDemand..normalised?

### ISSUE THREAD

**Issue by stevcabello** [uea-machine-learning/tsml_repo#14]
**Which dataset/datasets have you an issue with?**
ItalyPowerDemand

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)? **
timeseriesclassification.com

**Whats the issue?**
ItalyPowerDemand is supposed to have electrical power demand information, but I have noticed its time series contain lots of negative values. Does this dataset has been normalised? if so, between what range? e.g., [-5,5].

Thanks.

**Comment by TonyBagnall** [comment]
hi Steven, ItalyPowerDemand has been z-normalised (zero mean, unit standard dev). The UCR group formatted this, and described it here which can probably point you at the original source. Let us know if you need any further info. https://www.cs.ucr.edu/~eamonn/Intelligent_Icons.pdf

**Comment by stevcabello** [comment]
Thank you Tony

**Comment by TonyBagnall** [comment]
no problem, closing this issue now, feel free to ask more questions
