### ISSUE TITLE
[Website] https:// schema yields NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by thavlik** [uea-machine-learning/tsml_repo#15]
https://timeseriesclassification.com/TSC.zip has an invalid SSL certificate - just a heads up in case this happened recently and it hasn't been caught yet.

Thank you for the work!

**Comment by TonyBagnall** [comment]
thanks for that, I'll look into it.

**Comment by TonyBagnall** [comment]
we are going to fork out for SSL, thanks for raising this
