### ISSUE TITLE
[DONATION] InsectWingbeat dataset

### ISSUE THREAD

**Issue by MJFlynn** [uea-machine-learning/tsml_repo#17]
**Please give a brief description of the data**
The dataset was generated by the UCR computational entomology group. Instances are amplitude modulated intervals produced by the occlution of an infrared beam set within an enclosure housing a single specie of msquito.

**Where can we get the data?**
Original : https://sites.google.com/site/insectclassification/
Donated: the beast.

**Is there a publication related to the data**
Original
@article{chen2014flying,
  title={Flying insect classification with inexpensive sensors},
  author={Chen, Yanping and Why, Adena and Batista, Gustavo and Mafra-Neto, Agenor and Keogh, Eamonn},
  journal={Journal of insect behavior},
  volume={27},
  number={5},
  pages={657--677},
  year={2014},
  publisher={Springer}
}

**Is your data multivariate or univariate?**
Univariate

**Is there a default train/test split for the data**
No

**Are there any missing values/padding?**
No

**Is there a picture for the data we can put on the website?**
TBC

**How would you like the donation attributed on the website?**

**Can you provide a paragraph description, including the meaning of the class values, for the website?**
The dataset was generated by the UCR computational entomology group. Instances are amplitude modulated intervals produced by the occlution of an infrared beam set within an enclosure housing a single specie of mosquito. The dataset consists of 10 classes: four species of mosquito, Ae. aegypti, Cx. tarsalis, Cx. quinquefasciants, Cx. stigmatosoma sperated by sex and two species of fly, Musca domestica and Drosophila simulans. The class distribution is balanced with each class comprising of 5000 instances and 600 attributes. 

The dataset was produced with a sample rate of 16,000Hz and all extracted signals were centre padded in 1 second clips.
The dontated dataset consists of the centeral 10ms segment downsampled to 6,000Hz. This reverses the the post processing applied during the initial creation of the dataset (instances were extracted via a 10ms sliding window over the raw data) and leverages the expert knowledge that mosqutioes do not produce signals in excess of 2,000Hz.

**Comment by TonyBagnall** [comment]
@MJFlynn is this the same as this one?
https://www.timeseriesclassification.com/description.php?Dataset=InsectWingbeat

**Comment by TonyBagnall** [comment]
renamed InsectSound https://timeseriesclassification.com/description.php?Dataset=InsectSound
