### ISSUE TITLE
[DONATION] MosquitoWingbeat

### ISSUE THREAD

**Issue by MJFlynn** [uea-machine-learning/tsml_repo#18]
**Please give a brief description of the data**
The database contains wav recordings from the same optical sensor inserted in-turn into six insectary boxes containing only one mosquito species of both sexes. As the mosquitoes fly randomly through the sensor their wingbeat partially occludes the light from the transmitter to the receiver. The light fluctuation recorded follows the rhythm of the wingbeat.

**Where can we get the data?**
Original: https://www.kaggle.com/potamitis/wingbeats
Donated: The beast.

**Is there a publication related to the data**
@article{potamitis2016large,
  title={Large aperture optoelectronic devices to record and time-stamp insects’ wingbeats},
  author={Potamitis, Ilyas and Rigakis, Iraklis},
  journal={IEEE Sensors Journal},
  volume={16},
  number={15},
  pages={6053--6061},
  year={2016},
  publisher={IEEE}
}

**Is your data multivariate or univariate?**
Univariate

**Is there a default train/test split for the data**
No

**Are there any missing values/padding?**
No

**Is there a picture for the data we can put on the website?**
TBC

**How would you like the donation attributed on the website?**
TBC

**Can you provide a paragraph description, including the meaning of the class values, for the website?**
The database contains wav recordings from the same optical sensor inserted in-turn into six insectary boxes containing only one mosquito species of both sexes. As the mosquitoes fly randomly through the sensor their wingbeat partially occludes the light from the transmitter to the receiver. The light fluctuation recorded follows the rhythm of the wingbeat. Insect Biometrics, in the context of our work, is a measurable behavioral characteristic of flying insects. Biometric identifiers are related to the shape of the body (main body size, wing shape, wingbeat frequency, pattern movement of the wings). Biometric identification methods use biometric characteristics or traits to verify species/sex identities when insects access endpoint traps following a bait.

• 279,566 wingbeat recordings correctly labeled

• 6 mosquito species (Ae. aegypti, Ae. albopictus, An. arabiensis, An. gambiae, Cu. pipiens, Cu. quinquefasciatus)

**Comment by TonyBagnall** [comment]
its a monster https://timeseriesclassification.com/description.php?Dataset=InsectSound
