### ISSUE TITLE
[DONATION] CatsDogs

### ISSUE THREAD

**Issue by MJFlynn** [uea-machine-learning/tsml_repo#19]
**Please give a brief description of the data**
A dataset consisting of 277 instances. Each instance has eitehr a cat or dog label.

**Where can we get the data?**
Original: https://www.kaggle.com/mmoreaux/audio-cats-and-dogs
Donated: The beast.

**Is there a publication related to the data**
@article{takahashi2016deep,
  title={Deep convolutional neural networks and data augmentation for acoustic event detection},
  author={Takahashi, Naoya and Gygli, Michael and Pfister, Beat and Van Gool, Luc},
  journal={arXiv preprint arXiv:1604.07160},
  year={2016}
}

**Is your data multivariate or univariate?**
Univariate

**Is there a default train/test split for the data**
No

**Are there any missing values/padding?**
No

**Is there a picture for the data we can put on the website?**
No

**How would you like the donation attributed on the website?**
TBC

**Can you provide a paragraph description, including the meaning of the class values, for the website?**
A dataset consisting of 277 instances. Each instance has either a cat or dog label.
The data set has been truncated to the shortest instance.

- Cat: 163 instances.
- Dog: 113 instances.
- Attributes: 14773

**Comment by TonyBagnall** [comment]
done
https://www.timeseriesclassification.com/description.php?Dataset=CatsDogs
