### ISSUE TITLE
[BUG] Last value in PLAID dataset all seem to be zero

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml_repo#2]
Patrick adds
![image](https://user-images.githubusercontent.com/9594042/61828896-a5e6c000-ae5f-11e9-8512-013b3bd2154d.png)

**Comment by MatthewMiddlehurst** [comment]
While this is the case for a significant portion of the dataset instances (2/3), we are reluctant to call it a bug with how the data was processed and wont be making changes for now.

**Comment by TonyBagnall** [comment]
removed the last zeros and corrected the class meaning description
