### ISSUE TITLE
[DONATION] DuckDuckGeese

### ISSUE THREAD

**Issue by MJFlynn** [uea-machine-learning/tsml_repo#20]
**Please give a brief description of the data**
Dataset created from the recordings of wild ducks and geese. Recordings were not sampled from a specific geographcal area or limited to a single recording device.

**Where can we get the data?**
Donated: The beast

**Is there a publication related to the data**
Original (individual recordings) 
misc{TermsofU50:online,
author = {},
title = {Terms of Use :: xeno-canto},
howpublished = {\url{https://www.xeno-canto.org/about/terms}},
month = {},
year = {},
note = {(Accessed on 09/26/2018)}
}

**Is your data multivariate or univariate?**
Univariate

**Is there a default train/test split for the data**
No

**Are there any missing values/padding?**
No

**Is there a picture for the data we can put on the website?**
TBC

**How would you like the donation attributed on the website?**
Michael Flynn

**Can you provide a paragraph description, including the meaning of the class values, for the website?**
This data set was derived from recordings found on www.xenocanto.com. Each recording was taken from either the A or B quality catagory. Due to the variation in recorded sample rate all recordings were downsampled to 44100Hz using Matlabs resample function and then truncated to the shortest series length.

The classes are as follows:
Black-bellied Whistling Duck (20 instances)
Canadian Goose (20 instances)
Greylag Goose (20 instances)
Pink Footed Goose (20 instances)
White-faced Whistling Duck (20 instances)

Attributes: 236,784

**Comment by TonyBagnall** [comment]
changed the name to differentiate it from the multivariate version
