### ISSUE TITLE
[DONATION] AbnormalHeartbeat

### ISSUE THREAD

**Issue by MJFlynn** [uea-machine-learning/tsml_repo#22]
**Please give a brief description of the data**
Heartbeat recordings gathered from both the iStethoscope Pro iPhone app and from clinic trials in hosptials using the the digital stethoscope DigiScope.

**Where can we get the data?**
Original: https://www.kaggle.com/kinguistics/heartbeat-sounds#set_a.csv
Donated: The beast

**Is there a publication related to the data**
@misc{pascal-chsc-2011, author = "Bentley, P. and Nordehn, G. and Coimbra, M. and Mannor, S.", title = "The {PASCAL} {C}lassifying {H}eart {S}ounds {C}hallenge 2011 {(CHSC2011)} {R}esults", howpublished = "http://www.peterjbentley.com/heartchallenge/index.html"}

**Is your data multivariate or univariate?**
Univariate

**Is there a default train/test split for the data**
No

**Are there any missing values/padding?**
No

**Is there a picture for the data we can put on the website?**
TBC

**How would you like the donation attributed on the website?**
TBC

**Can you provide a paragraph description, including the meaning of the class values, for the website?**

Heartbeat recordings gathered from both the iStethoscope Pro iPhone app and from clinic trials in hosptials using the the digital stethoscope DigiScope.

All instances were resampled to 4,000Hz and truncated to the shortest instance length.

Instances: 606
Attributes: 3,053
Classes: 
- Artifact (40)
- ExtraStole (46)
- Murmur (129)
- Normal (351)
- ExtraHLS (40)

**Comment by TonyBagnall** [comment]
done, class values different to the above though
https://www.timeseriesclassification.com/description.php?Dataset=AbnormalHeartbeat
