### ISSUE TITLE
[DONATION] UrbanSounds

### ISSUE THREAD

**Issue by MJFlynn** [uea-machine-learning/tsml_repo#23]
**Please give a brief description of the data**
The UrbanSound dataset comprises of real world sounds.  
**Where can we get the data?**
Donated: The beast

**Is there a publication related to the data**
No

**Is your data multivariate or univariate?**
Univariate

**Is there a default train/test split for the data**
No

**Are there any missing values/padding?**
No

**Is there a picture for the data we can put on the website?**
TBC

**How would you like the donation attributed on the website?**
TBC

**Can you provide a paragraph description, including the meaning of the class values, for the website?**

Dataset was resampled to 44,100Hz (the most common sample rate) and truncated/center padded to one second. 
Attributes: 44,100
Instances: 5,435
Classes: 10
- Air_conditioner (600)
- Car_horn (306)
- Children_playing (600)
- Dog_bark (600)
- Drilling (600)
- Engine_idling (624)
- Gun shot (230)
- Jackhammer (668)
- Siren (607)
- Street_music (600)

**Comment by TonyBagnall** [comment]
https://timeseriesclassification.com/description.php?Dataset=UrbanSound
