### ISSUE TITLE
[DONATION] FruitFlies

### ISSUE THREAD

**Issue by MJFlynn** [uea-machine-learning/tsml_repo#24]
**Please give a brief description of the data**
Dataset comripising of three speicies of fruit fly. 

**Where can we get the data?**
The beast

**Is there a publication related to the data**
No

**Is your data multivariate or univariate?**
Univariate

**Is there a default train/test split for the data**
No

**Are there any missing values/padding?**
No

**Is there a picture for the data we can put on the website?**
TBC

**How would you like the donation attributed on the website?**
Ilyas Pontamitis

**Can you provide a paragraph description, including the meaning of the class values, for the website?**

Dataset comripising of three speicies of fruit fly, Dr. melanogaster, Dr. suzukii and Zaprionus of unknown species! (Couldn't be identified with molecular methods). The dataset was recorded wih a sample rate of 8,000Hz.

Atributes: 5,000
Instances: 34,518
Classes:
-  melanogaster (6,064)
- suzukii (10,142)
- zaprionus (18,312)

**Comment by TonyBagnall** [comment]
@MJFlynn do you have a link for this data?

**Comment by TonyBagnall** [comment]
https://timeseriesclassification.com/description.php?Dataset=FruitFlies
