### ISSUE TITLE
Possible Dataset for inclusion

### ISSUE THREAD

**Issue by EngrStudent** [uea-machine-learning/tsml_repo#26]
This isn't a donation.  I don't own the data.  I think the data is owned by "the American public" but I'm not sure.

Link:

- https://www.sdms.afrl.af.mil/index.php?collection=wide_angle_sar

Points:
- it is larg(er) data: tens of thousands of columns per sample
- it is multivariate
- it is physically concrete, so there is a clear mechanistic analog that allows easier comprehension
- progress in the area has economic value (google says there are 20 citations of the data-paper, and of those only a few are applied to classification)
- it is a time-series that translates in several different ways into images (see utility code)

**Comment by EngrStudent** [comment]
Here is another SAR-based geospatial dataset repository.  They collect a lot of NASA ground-looking radar information and disseminate it.  I didn't see any license page, but perhaps it is in one of the manuals at the bottom of the page.

Link: https://www.asf.alaska.edu/get-started-2/#daac_data

**Comment by TonyBagnall** [comment]
hi, its only taken 8 months to look at this, sorry! This data is interesting but only available for those with a US address, and I'm not sure we would be able to put it up on our repo?

**Comment by TonyBagnall** [comment]
I dont think we can use this,
