### ISSUE TITLE
[DONATION] Time series of colposcopy

### ISSUE THREAD

**Issue by KarinaGF** [uea-machine-learning/tsml_repo#27]
**Please give a brief description of the data**
The data includes the intensity values ​​of a pixel region through a sequence of digital colposcopic images obtained during the colposcopy test, which is commonly used for the diagnosis of cervical cancer.

**Where can we get the data?**
https://github.com/KarinaGF/ColposcopyData
kgutierrezf@gmail.com

**Is there a publication related to the data**
Computational and Mathematical Methods in Medicine
Volume 2017, Article ID 5989105, 10 pages
https://doi.org/10.1155/2017/5989105
Optimization of Classification Strategies of Acetowhite Temporal Patterns towards Improving Diagnostic Performance of Colposcopy

**Is your data multivariate or univariate?**
Univariate

**Is there a default train/test split for the data**
No

**Are there any missing values/padding?**
No

**Is there a picture for the data we can put on the website?**
TBC

**How would you like the donation attributed on the website?**
Karina Gutiérrez-Fragoso,1 Héctor Gabriel Acosta-Mesa,2 Nicandro Cruz-Ramírez,2 and Rodolfo Hernández-Jiménez3
1 Biomedical Research Center, Universidad Veracruzana, Xalapa, VER, Mexico
2 Artificial Intelligence Research Center, Universidad Veracruzana, Xalapa, VER, Mexico
3 Obstetrician and Gynecologist, Private Practice, Xalapa, VER, Mexico
Correspondence should be addressed to Karina Gutiérrez-Fragoso; kgutierrez@itesa.edu.mx

*Can you provide a paragraph description, including the meaning of the class values, for the website?**
Instances: 200
Attributes: 182
Column 1 represents a patient ID
Column 2 represents the class
Classes:
•	Value 1 represents “atrophy” and include 15 cases
•	Value 2 represents “inflammation” and include 24 cases
•	Value 3 represents “ectopy” and include 20 cases
•	Value 4 represents “normal” and include 48 cases
•	Value 5 represents “low-grade squamous intraepithelial lesion (LSIL)” and include 37 cases
•	Value 5 represents “high-grade squamous intraepithelial lesion (LSIL)” and include 56 cases
Columns 3 to 182 represent the change in intensity values of a pixel region through a sequence of digital colposcopic images obtained during the colposcopy test that was performed on each patient included in the study.

**Comment by TonyBagnall** [comment]
hi, thanks very much for the donation, we will get on it and get back to you if we have any formatting issues

**Comment by TonyBagnall** [comment]
https://www.timeseriesclassification.com/description.php?Dataset=Colposcopy
