### ISSUE TITLE
Bug in MelbournePedestrian dataset

### ISSUE THREAD

**Issue by johnpaparrizos** [uea-machine-learning/tsml_repo#3]
Hello,

I think the MelbournePedestrian dataset has a bug: in both training and test sets, there are multiple rows where all values are '-1'. Maybe it indicates missing values? However, the fact that the whole row has such values make the reconstruction of such time series impossible. Maybe consider removing those rows.

Best,
John

**Comment by TonyBagnall** [comment]
thanks John, we will sort it out.

**Comment by MatthewMiddlehurst** [comment]
Given the context of the dataset I would agree that these are missing values. We will remove rows only containing missing values and replace occurrences of -1 with ? in the ARFF and TS files.

**Comment by TonyBagnall** [comment]
I'll close when I've uploaded the correct version :)

**Comment by TonyBagnall** [comment]
we have deleted some cases and also realised that there are in fact missing values in this dataset. These are now correctly recorded. Corrected version is now here, and will be in the full download tomorrow
http://www.timeseriesclassification.com/description.php?Dataset=MelbournePedestrian
