### ISSUE TITLE
[ISSUE]The reproduced results in UCR

### ISSUE THREAD

**Issue by peter943** [uea-machine-learning/tsml_repo#37]
Hi 
   I am a student working for the time series classification. I download the ucr achrive from the http://www.timeseriesclassification.com/. I want to reproduce the results by DTW (window size =100), but I find in some datasets, the reproduced results is unequal to the results provided in csv (download from http://www.timeseriesclassification.com/results.php). For example, in the  BirdChicken, the accuracy in csv is 75% which is lower than 95% I reproduced. I use the code from https://github.com/pierre-rouanet/dtw and and set w=100 and  dist=manhattan_distance to calculate the dtw distance. I simply use a double loop to achieve a 1NN classifier. I do not know the reason for this discrepancy. Could you please give me some help? Thanks a lot.

**Comment by peter943** [comment]
Sorry, I find a small mistake in my code. I achieve the 75% accuracy after I correct my code.

**Comment by TonyBagnall** [comment]
hi, its been a long time, but I'm pretty sure we use Euclidean distance not Manhattan

**Comment by TonyBagnall** [comment]
fyi, there is a python toolkit fot time series classification here, we welcome contributors https://github.com/alan-turing-institute/sktime

**Comment by peter943** [comment]
> fyi, there is a python toolkit fot time series classification here, we welcome contributors https://github.com/alan-turing-institute/sktime

Thanks for your kind help. I know the UCR has been updated many times. I wonder if the results on the http://www.timeseriesclassification.com correspond to the latest version of the UCR.

**Comment by TonyBagnall** [comment]
the results are those we used in the bake off paper. We are currently updating the bake off for some new algorithms, should be done early next year, I'll update the results pages then

**Comment by peter943** [comment]
> the results are those we used in the bake off paper. We are currently updating the bake off for some new algorithms, should be done early next year, I'll update the results pages 
Thanks a lot. It was great help. I am working on the time series classification of varying length data sets. I download the paper "The UCR Time Series Classification Archive". According to my understanding, authors added low amplitude random numbers (to the end) to the length of the longest time series to make all time series of equal length and then used dtw to construct the dtw baseline for the varying length datasets (which have been padded).  I don't know if my understanding is correct

**Comment by TonyBagnall** [comment]
all the results have been recreated for many classifiers, see here for more info
https://www.timeseriesclassification.com/results.php
