### ISSUE TITLE
Commercial Use

### ISSUE THREAD

**Issue by WilliamHoltam** [uea-machine-learning/tsml_repo#38]
**Which dataset/datasets have you an issue with?**
All datasets.

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)? **
timeseriesclassification.com

**Whats the issue?**
The licence on the Git repo is GPL. Are the datasets able to be used for commercial use?

**Comment by TonyBagnall** [comment]
So I didnt see this, I'm very sorry. The datasets are as far as I know open to all, I suggest you contact Eamonn Keogh at UCR to check with him
