### ISSUE TITLE
Issues downloading and loading a couple of datasets

### ISSUE THREAD

**Issue by johannfaouzi** [uea-machine-learning/tsml_repo#4]
Hi,

I've been working recently with the UCR and UEA archives. I have some issues with two datasets from the UEA archive:

* EigenWorms: I cannot unzip the downloaded file,
* SpokenArabicDigits: thefunction that I use to read the datasets doesn't work on this one, while it works for all the other datasets.

All the files were downloaded individually from http://www.timeseriesclassification.com/index.php
All the other datasets work perfectly.

Best,
Johann

**Comment by MatthewMiddlehurst** [comment]
Hi Johann,

Thanks for informing us. For your second issue what files are you attempting to read? If it is the .TS files it looks like the test set is missing which may be causing the issue. If not will have a look a little deeper.
Either way we will work towards fixing both downloads.

Thanks,
Matthew

**Comment by johannfaouzi** [comment]
Thank you for your reply. I'm using the ARFF files, and I can't load it using [scipy.io.arff.loadarff](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.arff.loadarff.html). It fails for the training set. I have not tested on the test set.

```python
from scipy.io.arff import loadarff

loadarff('SpokenArabicDigits_TRAIN.arff')

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in loadarff(f)
    736         ofile = open(f, 'rt')
    737     try:
--> 738         return _loadarff(ofile)
    739     finally:
    740         if ofile is not f:  # only close what we opened

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in _loadarff(ofile)
    801             yield tuple([attr[i].parse_data(row[i]) for i in elems])
    802 
--> 803     a = list(generator(ofile))
    804     # No error should happen here: it is a bug otherwise
    805     data = np.array(a, [(a.name, a.dtype) for a in attr])

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in generator(row_iter, delim)
    799             row, dialect = split_data_line(raw, dialect)
    800 
--> 801             yield tuple([attr[i].parse_data(row[i]) for i in elems])
    802 
    803     a = list(generator(ofile))

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in <listcomp>(.0)
    799             row, dialect = split_data_line(raw, dialect)
    800 
--> 801             yield tuple([attr[i].parse_data(row[i]) for i in elems])
    802 
    803     a = list(generator(ofile))

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in parse_data(self, data_str)
    377 
    378         for raw in escaped_string.split("\n"):
--> 379             row, self.dialect = split_data_line(raw, self.dialect)
    380 
    381             row_tuples.append(tuple(

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in split_data_line(line, dialect)
    413 
    414     # Remove the line end if any
--> 415     if line[-1] == '\n':
    416         line = line[:-1]
    417 

IndexError: string index out of range
```

**Comment by MatthewMiddlehurst** [comment]
There was an issue with the final relation containing a \n which it didn't like. Loading the dataset should be fine in both Java and using the scipy loading function. Will close the issue when the fix has been uploaded.

**Comment by TonyBagnall** [comment]
hi Johann, should be working now 
EigenWorms
http://www.timeseriesclassification.com/description.php?Dataset=EigenWorms
SpokenArabicDigits
http://www.timeseriesclassification.com/description.php?Dataset=SpokenArabicDigits
let us know if you have any other problems
