### ISSUE TITLE
[DONATION] ICANN 2011 Mind Reading Challenge Dataset (MEG)

### ISSUE THREAD

**Issue by craftycodie** [uea-machine-learning/tsml_repo#54]
**Please give a brief description of the data**
A subject was shown various types of video without audio.

727 Train Instances
653 Test Instances
204 Channels
200 Series Length
5 Classes (the types of video)

**Where can we get the data?**
http://www.cis.hut.fi/icann11/meg/measurements.html
icann2011.meg@cis.hut.fi

**Is there a publication related to the data**
http://www.cis.hut.fi/icann11/meg/megicann_klamietal.pdf
http://www.cis.hut.fi/icann11/meg/megicann_proceedings.pdf

**Is your data multivariate or univariate?**
multivariate

**Is there a default train/test split for the data**
yes

**Are there any missing values/padding?**
no

**Is there a picture for the data we can put on the website?**

**How would you like the donation attributed on the website?**

**Can you provide a paragraph description, including the meaning of the class values, for the website?**
"We recorded MEG signals from one healthy 25-yrs old male. The Subject was shown different types of video without audio. These types (and the classes of data) are: artificial; natural; football; Bean; and Chaplin."

**Comment by codieradical** [comment]
I've got a script to convert these MAT files to ARFF which might be useful too.

**Comment by TonyBagnall** [comment]
hi, thanks a lot for this, sorry it took us two years to sort it! Data is here https://timeseriesclassification.com/description.php?Dataset=MindReading
