### ISSUE TITLE
resample dataset

### ISSUE THREAD

**Issue by frankl1** [uea-machine-learning/tsml_repo#56]
Hi,

Thank you for releasing the latest results. 

Can you tell me how you created the 30 resample datasets ?

In the result files, which fold is the original train/test split ?

Thanks in advance

**Comment by MJFlynn** [comment]
Hi,

The resamples are created via this method: `public static Instances[] sampleDataset(String parentFolder, String problem, int fold)` in the DatasetLoading class.

The folds are generated via using seed values 0 - 29.

If there is a 0th fold train and test files defined in the provided path destination, then that is used for the first fold. For the rest of the folds, the 0th fold train and test are combined and resampled randomly (seeded) maintining the original class distribution from the 0th fold.

If all the data is in one file (not initial train/test split). The distribution is default 0.5.

The result files labbels correspond to the train file labels. e.g. seed 0 -> train/test fold 0 -> result file 0.

Hope that helps?

**Comment by frankl1** [comment]
Yes, you couldn't be clearer.
Thank you very much
