### ISSUE TITLE
[ISSUE] DuckDuckGeese files are nested unexpectedly

### ISSUE THREAD

**Issue by felixdivo** [uea-machine-learning/tsml_repo#57]
**Which dataset/datasets have you an issue with?**
*DuckDuckGeese*

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)?**
From timeseriesclassification.com: https://www.timeseriesclassification.com/Downloads/DuckDuckGeese.zip

**Whats the issue?**
It seems like in the case of most datasets, the test, train and meta files are directly embedded into the main zip file. (Tested with `Handwriting`, `TwoPatterns`, `StarLightCurves`, `CinCECGTorso` and `PenDigits`.) However, in the case of `DuckDuckGeese`, the `DuckDuckGeese_TRAIN.arff` and `DuckDuckGeese_TEST.arff` files are nested within a `DuckDuckGeese/` directory that is within the `DuckDuckGeese.zip` file. Is that intentional or could this be changed to not be nested?

For some context: The [*tslearn* library](https://github.com/tslearn-team/tslearn/) contains [some tools](https://tslearn.readthedocs.io/en/stable/gen_modules/datasets/tslearn.datasets.UCR_UEA_datasets.html#tslearn.datasets.UCR_UEA_datasets) for easily downloading these datasets. However, it fails with the *DuckDuckGeese* dataset because of the slightly different file structure. If this nesting was not intentional, it would be great if it were possible to change it on the timeseriesclassification.com side of it.

**Comment by TonyBagnall** [comment]
hi, its not intentional, just a random thing. I'll add it to my list to correct

**Comment by felixdivo** [comment]
> hi, its not intentional, just a random thing. I'll add it to my list to correct

Thanks! That'll make things easier.

**Comment by felixdivo** [comment]
@TonyBagnall Could you estimate when this will be fixed? Thanks!

**Comment by TonyBagnall** [comment]
hi, I have now unnested all problems and have run through downloading them all using the download function in sktime, so I'll close this, sorry for how long it took me!

**Comment by felixdivo** [comment]
Nice, thank you for remembering!
