### ISSUE TITLE
[Website] Univariate Summary CSV

### ISSUE THREAD

**Issue by imartinezl** [uea-machine-learning/tsml_repo#58]
please note timeseriesclassification.com is maintained when we have time, and none of us are web developers. If you want to help develop it let us know.

**whats the issue or suggestion?**

The univariate summary description csv file [http://www.timeseriesclassification.com/Downloads/Archives/summaryUnivariate.csv]()
has the columns "numTestCases" and  "seriesLength" joined together. There should be a comma between those fields.

![image](https://user-images.githubusercontent.com/20516006/103234563-4a680e00-4940-11eb-8186-5e1bdc4f8514.png)

**Comment by TonyBagnall** [comment]
fixed thanks
