### ISSUE TITLE
Data donation (multivariate)

### ISSUE THREAD

**Issue by vmasouza** [uea-machine-learning/tsml_repo#6]
Hi everyone,
I would like to donate for this repository, three of my multivariate time series data (4-dimensional). These data were obtained by an accelerometer sensor from smartphones during car driving over different conditions.

You can download the datasets (MAT-File) in the following link: 
http://sites.labic.icmc.usp.br/vsouza/repository/EAAI_datasets.zip

A more detailed description of them can be found in the following paper (it is also the reference for the data):
https://www.sciencedirect.com/science/article/pii/S0952197618301349

The data were not normalized or pre-processed, so each series has a different length. Feel free to process them to make it available in the repository with the given reference.

Please feel free to contact me if you need any further information or some help to describe such data in a future updated version of the Arxiv document.

Regards

**Comment by TonyBagnall** [comment]
thanks very much for this, we will let you know how we get on and close this issue when we have formatted them.

**Comment by TonyBagnall** [comment]
hi @vmasouza, the data is not split into train/test, are there any constraints on this (such as different subjects that should not be in train and test), or shall we just do it randomly?

**Comment by TonyBagnall** [comment]
hi, could we also but versions in the univariate archive? 
![image](https://user-images.githubusercontent.com/9594042/62774059-b1f79200-ba9b-11e9-81f8-dbf412f6f444.png)

**Comment by vmasouza** [comment]
Hi @TonyBagnall 

Well noted, I forgot that I applied the Butterworth filter. So, the available data were pre-processed, and they are similar to a z-normalized version. However, probably you will still need to stretch or shorten the series to obtain the same length. Note that in some cases, we have a significative difference between the series length. If you have a simple solution to do this, please let me know.

It seems to be a good idea to use the series Ax, Ay, Az for a multivariate version of the datasets and only the Am as a univariate version, since it is the result of a composition of the three axes.

The data don't have any constraint to split into training/test. In my experiments, I did partition the datasets into training/test and repeated five times randomizing the order of examples between executions (5x2-cross validation). If you need to know the exact proportion of the split, I can verify in my codes (it was probably 50/50). But, feel free to change it for a more difficult setting.

**Comment by TonyBagnall** [comment]
hi, our philosophy now is to do as little preprocessing ourselves as possible, so we will keep them unequal length. Matthew has formatted them, and we intend calling them AsphaltPavementType, AsphaltObstacles and AsphaltRegularity in the univariate version (the Am series) and  AsphaltPavementTypeCoordinates, AsphaltObstaclesCoordinates and AsphaltRegularityCoordinates in the multivariate one (the X,Y,Z series). I'll take some text and images from your paper if thats ok. We will do a random 50/50 train test split. I'll get them on the website fairly soon and give you a link to vet. They can go in the whole zip at the next batch release.

**Comment by vmasouza** [comment]
Hi Tony, it seems to be good! You can use the images from the paper.

**Comment by TonyBagnall** [comment]
so they are all now formatted and up on the website. Take a look here.
