### ISSUE TITLE
[ISSUE] LargeKitchenAppliances dataset

### ISSUE THREAD

**Issue by stevcabello** [uea-machine-learning/tsml_repo#60]
**Which dataset/datasets have you an issue with?**
LargeKitchenAppliances

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)? **
timeseriesclassification.com

**Whats the issue?**
LargeKitchenAppliances has three class labels: 1,2,3. I'd will like to know which appliance is 1, 2 and 3.

According to the website (i.e., timeseriesclassification.com) the class labels are: Washing Machine, Tumble Dryer and Dishwasher. However, a specific order is not given
<img width="819" alt="image" src="https://user-images.githubusercontent.com/5056125/112566334-da7bfd80-8e32-11eb-8992-584fafac4cfe.png">

In the paper: "Ensembles of Elastic Distance Measures for Time Series Classification", Table 2 shows a different order:
Dishwasher, Tumble Dryer and Washing Machine.
![image](https://user-images.githubusercontent.com/5056125/112566199-9f79ca00-8e32-11eb-9148-abedf8fa0958.png)

Read More: https://epubs.siam.org/doi/abs/10.1137/1.9781611973440.60

**Comment by TonyBagnall** [comment]
hi, I'm having a dig around in backups, as I'm not sure! I'll get back to you

**Comment by TonyBagnall** [comment]
ok, 18 months later ... I found the originally formatted files and can confirm the classes are 
 Washing Machine (1), Dishwasher (2) and Tumble Dryer (3). Note to self, the original, unnormalised, data are on the central file storage (U drive normally) in dir , "TSC Problems Old". Website updated http://timeseriesclassification.com/description.php?Dataset=LargeKitchenAppliances
