### ISSUE TITLE
[ISSUE] Cannot download ERing from timeseriesclassification.com

### ISSUE THREAD

**Issue by johannfaouzi** [uea-machine-learning/tsml_repo#61]
**Which dataset/datasets have you an issue with?**

ERing

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)?**

http://www.timeseriesclassification.com/description.php?Dataset=ERing

**Whats the issue?**

The link to download the dataset does not work anymore.

**Comment by TonyBagnall** [comment]
thanks, I'll check it out

**Comment by TonyBagnall** [comment]
sorted now
