### ISSUE TITLE
[ISSUE] Cannot load Tiselac dataset using scipy.io.arff.loadarff

### ISSUE THREAD

**Issue by johannfaouzi** [uea-machine-learning/tsml_repo#62]
**Which dataset/datasets have you an issue with?**

Tiselac

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)?**

http://www.timeseriesclassification.com/description.php?Dataset=Tiselac

**Whats the issue?**

Loading this dataset using [scipy.io.arff.loadarff](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.arff.loadarff.html), while it works for the other datasets. I'm not knowledgeable enough about ARFF files to know what is the issue.

**Comment by TonyBagnall** [comment]
hi, cant help with scipy, sorry, never used it. Does it throw and exception? Does it work with other multivariate problems?

**Comment by johannfaouzi** [comment]
Yes it throws the following exception:

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-aaeb87c6f6c2> in <module>
      1 from scipy.io.arff import loadarff
      2 
----> 3 loadarff('/Users/johann.faouzi/UCR_UEA_temp/Tiselac/Tiselac_TRAIN.arff')

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in loadarff(f)
    803         ofile = open(f, 'rt')
    804     try:
--> 805         return _loadarff(ofile)
    806     finally:
    807         if ofile is not f:  # only close what we opened

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in _loadarff(ofile)
    868             yield tuple([attr[i].parse_data(row[i]) for i in elems])
    869 
--> 870     a = list(generator(ofile))
    871     # No error should happen here: it is a bug otherwise
    872     data = np.array(a, [(a.name, a.dtype) for a in attr])

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in generator(row_iter, delim)
    866             row, dialect = split_data_line(raw, dialect)
    867 
--> 868             yield tuple([attr[i].parse_data(row[i]) for i in elems])
    869 
    870     a = list(generator(ofile))

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in <listcomp>(.0)
    866             row, dialect = split_data_line(raw, dialect)
    867 
--> 868             yield tuple([attr[i].parse_data(row[i]) for i in elems])
    869 
    870     a = list(generator(ofile))

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in parse_data(self, data_str)
    372 
    373         for raw in escaped_string.split("\n"):
--> 374             row, self.dialect = split_data_line(raw, self.dialect)
    375 
    376             row_tuples.append(tuple(

~/anaconda3/lib/python3.7/site-packages/scipy/io/arff/arffread.py in split_data_line(line, dialect)
    474 
    475     # Remove the line end if any
--> 476     if line[-1] == '\n':
    477         line = line[:-1]
    478 
IndexError: string index out of range
```
So `line` is a string, but probably an empty string since returning the last character in the string (line[-1]) raises an string index error.

The scipy.io.arff.loadarff works perfectly fine for all the other UEA datasets (PhonemeSpectra for instance), so I would assume that the issue comes from the files of the Tiselac dataset instead.

**Comment by johannfaouzi** [comment]
Ok, so I dug deeper and for the Tiselac files, at the end of each row, there is a `\n` character before the class label, which is not present in the files of the other datasets. I would guess that the issue comes from there.

For example, here are the last characters of the first sample in different files:
* EyesOpenShut_TRAIN.arff: 4356.41,4354.36,4353.33',0
* PhonemeSpectra_TRAIN.arff: 1.9058,13.368,12.279,1.3264',AA
* Tiselac_TRAIN.arff: 469,469,469,469,469\n',6

**Comment by TonyBagnall** [comment]
ah yes that makes sense, we had a format change some time ago, tiselac was a later edition but did not get reformatted.  I'll add it to my list and post here once reformatted

**Comment by TonyBagnall** [comment]
so only took me a year and a half, should work now though http://timeseriesclassification.com/description.php?Dataset=Tiselac
