### ISSUE TITLE
Classes for ECG200 and GunPoint

### ISSUE THREAD

**Issue by rami-mochaourab** [uea-machine-learning/tsml_repo#63]
The dataset ECG200 has two classes, -1 and 1, which represent normal heartbeat and myocardial infarction. I could not find the description about which class represents which case. Is class -1 representing normal heartbeat? Similarly in the dataset GunPoint, does class 1 represent Gun-Draw?

**Comment by TonyBagnall** [comment]
I'll take a look

**Comment by TonyBagnall** [comment]
So  I've had a look and cant find a definitive answer. I would assume that 1 is "positive", so indicates Gun-Draw and Infarction, but I cannot confirm, this data all can from UCR. I'll ask Eamonn

**Comment by TonyBagnall** [comment]
For GunPoint, class 1 represent no gun, class 2 represents gun. Updated here http://timeseriesclassification.com/description.php?Dataset=GunPoint

**Comment by skafai** [comment]
@TonyBagnall : What about the ECG200 dataset. I still cannot find a definite answer or a source for:

-  "-1" being the normal heartbeat.
-  "1" being the "Myocardial infarction".

Can you please confirm this?
