### ISSUE TITLE
[ISSUE] JapaneseVowels unequal length

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [uea-machine-learning/tsml_repo#66]
**Which dataset/datasets have you an issue with?**

The  JapaneseVowels dataset description states: "originally a length between 7 and 29. In this dataset, instances have been padded to the longest length, 29". The dataset is unequal length however (or at least the .arff files have missing values at the end of the series).

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)?**

website and sktime versions of the dataset

**Comment by TonyBagnall** [comment]
ts files now unequal length
