### ISSUE TITLE
[ISSUE]No ordering information for the dimensions of the BasicMotions or RacketSports datasets

### ISSUE THREAD

**Issue by olivercliff** [uea-machine-learning/tsml_repo#68]
The information states that there are accelerometer and gyroscope readings but it's unclear which order each of the dimension are (e.g., is it x-y-z-roll-pitch-yaw?). Perhaps include in multivariateSummary.csv or a readme.txt in the download folder?

This is the case for some other datasets but I'm only interested in these two for now.

**Comment by TonyBagnall** [comment]
*one year later* did some digging around old student projects and found the source code. The ordering  is accelerometer x, y, z then gyroscope x, y, z (assume thats roll-pitch-yaw). I have updated the pages for BasicMotions and RacketSports
http://timeseriesclassification.com/description.php?Dataset=BasicMotions

**Comment by olivercliff** [comment]
Thanks for following this up, Tony!
