### ISSUE TITLE
File missing in SpokenArabicDigits dataset

### ISSUE THREAD

**Issue by blafabregue** [uea-machine-learning/tsml_repo#7]
There is a file missing in a dataset of the Multivariate archive in sktime format (Multivariate2018_ts.zip), for the SpokenArabicDigits dataset : SpokenArabicDigits_TEST.ts

**Comment by MatthewMiddlehurst** [comment]
Thanks for creating the issue. We came across this in issue #4 and are currently working towards replacing the missing files. When we have uploaded them we will close the issue.

**Comment by TonyBagnall** [comment]
should all be there now, thanks. SpokenArabicDigits
http://www.timeseriesclassification.com/description.php?Dataset=SpokenArabicDigits

**Comment by TonyBagnall** [comment]
let us know if you have any more problems
