### ISSUE TITLE
Car and Plane - data origins update (source included)

### ISSUE THREAD

**Issue by jasonlines** [uea-machine-learning/tsml_repo#71]
We had an email query about the origins of the Plane dataset. I had a dig into it and found the original paper here:

https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1541295
 
_Thakoor, Ninad, and Jean Gao. "Shape classifier based on generalized probabilistic descent method with hidden Markov descriptor." Tenth IEEE International Conference on Computer Vision (ICCV'05) Volume 1. Vol. 1. IEEE, 2005._

This info isn't on the web yet and would be good to add. The paper also includes information about how the data was recorded (e.g. Plane was taken from model planes!) and this context would be good for the data description too

**Comment by TonyBagnall** [comment]
done https://timeseriesclassification.com/description.php?Dataset=Car https://timeseriesclassification.com/description.php?Dataset=Plane
