### ISSUE TITLE
[ISSUE] Classes for "Wine" dataset not explained

### ISSUE THREAD

**Issue by davnn** [uea-machine-learning/tsml_repo#74]
**Which dataset/datasets have you an issue with?**
Wine

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)? **
https://www.timeseriesclassification.com/description.php?Dataset=Wine

**Whats the issue?**
Unknown what the classes represent and the link does not lead to an explanation.

**Comment by TonyBagnall** [comment]
so I asked Kate about this, and she says this
"It is very old - early 90s! One thing I am certain of though is that they are triplicate measurements (i.e. three subsamples taken from each independent wine bottle) so the actual n for train and test are one third of what is listed there. The classes are 'Cabernet Sauvignon' and 'Shiraz'. If I manage to retrieve the details I will send on to you. "
is that sufficient @davnn ? Not sure which class is which though! I will update the files to reflect this.

**Comment by davnn** [comment]
That's perfect, thanks!
