### ISSUE TITLE
[ISSUE] ERing dataset not available

### ISSUE THREAD

**Issue by VincentSch4rf** [uea-machine-learning/tsml_repo#76]
**Which dataset/datasets have you an issue with?**
- ERing

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)?**
- timeseriesclassification.com

**Whats the issue?**
- When trying to download the `ERing` multivariate dataset from the  `timeseriesclassification.com` web server, instead of a “.zip” file containing the data set, the start page is retrieved. As far as I know, from working with this repository for some time, this indicates that the requested path does not exist.

**Comment by TonyBagnall** [comment]
should be ok now, there was an error in the file name
http://timeseriesclassification.com/description.php?Dataset=ERing

**Comment by VincentSch4rf** [comment]
Awesome! Works perfectly now.
