### ISSUE TITLE
CricketZ [Website]

### ISSUE THREAD

**Issue by DanWillisUni** [uea-machine-learning/tsml_repo#77]
please note timeseriesclassification.com is maintained when we have time, and none of us are web developers. If you want to help develop it let us know.

There are a few spelling errors in the the description of the data for https://timeseriesclassification.com/description.php?Dataset=CricketZ.

The spelling mistakes I spotted are highlighted in the image linked below.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/46418885/166430147-dc028893-a4c0-4b4d-8317-e926dda52032.png">

**Comment by TonyBagnall** [comment]
thanks for that, corrected now 
http://timeseriesclassification.com/description.php?Dataset=CricketX
