### ISSUE TITLE
[ISSUE]Question on UCR Datasets

### ISSUE THREAD

**Issue by Wwwwei** [uea-machine-learning/tsml_repo#78]
**Which dataset/datasets have you an issue with?**

**Where did you download the data from (e.g. UCR or timeseriesclassification.com)?**

**Whats the issue?**
I am trying to follow some _Shapelets_ work in time series classification, such as 

- [Learning time-series shapelets](https://dl.acm.org/doi/abs/10.1145/2623330.2623613?casa_token=NESErENbRecAAAAA:E6So99Q5pKDgHqGQL9oiG12qvPB1KEsL0xncGOK5qUjz1fHGevCtuiTJXPeiznTzdRdMPnmN2gq1qw)
- [Time series shapelets: a new primitive for data mining](https://dl.acm.org/doi/abs/10.1145/1557019.1557122?casa_token=WUBHJxQosUYAAAAA%3A876JnI4A3EN36a36p8vUrxhgX0RqJJXLi9u9cD0qTc6aRwdDGfQYv2TSEHBrZ_scs0ZOiFkcP9837g)
- [Adversarial Dynamic Shapelet Network](https://ojs.aaai.org/index.php/AAAI/article/view/5948)

I notice that following datasets are widely used in these work:

- DP_Little
- DP_Middle
- DP_Thumb
- MP_Little
- MP_Middle
- PP_Little
- PP_Middle
- PP_Thumb

However, I did not find them in http://www.timeseriesclassification.com/ (although the most authors state that the datasets came from UCR archive). I would like to know whether these datasets have been renamed or where I could get them. 

Any one help me? Thank you for your assistance.

**Comment by TonyBagnall** [comment]
hi, sorry for the slow response. Those datasets were used in the shaplet paper over ten years ago and came before we relaunched the archive. TBH I cannot remember how they were formatted, and they were basically deprecated in favour of the bone datasets in the relaunched repo.

**Comment by Wwwwei** [comment]
> hi, sorry for the slow response. Those datasets were used in the shaplet paper over ten years ago and came before we relaunched the archive. TBH I cannot remember how they were formatted, and they were basically deprecated in favour of the bone datasets in the relaunched repo.

Thanks a lot for your reply. I will try to contact the authors of the recent paper to see if they can share these datasets.
